# Change these first
owner: GeekCircuitOfficial # Your GitHub organization or username, where this repository lives
repo: StatusPage # The name of this repository

sites:
- name: GeekCircuit
  url: https://www.geekcircuit.com/
  check: "https"
  port: 443
  ipv6: false
  icon: https://assets.geekcircuit.com/img/favicon/favicon.png

- name: Tooloza
  url: https://tooloza.com/
  check: "https"
  port: 443
  ipv6: false

status-website:
  cname: status.geekcircuit.com
  logoUrl: https://assets.geekcircuit.com/img/logo/dark.svg
  name: Geek Circuit
  customHeadHtml: |
    <link rel="icon" type="image/png" href="https://assets.geekcircuit.com/img/favicon/favicon.png">
    <meta name="description" content="Stay updated with the real-time uptime status of GeekCircuit's online services and tools.">
    <meta name="keywords" content="GeekCircuit, Status, Monitoring, Uptime, India">
    <meta name="author" content="Jai Krishna Tavva">
    <meta property="og:title" content="GeekCircuit Status Page">
    <meta property="og:description" content="Stay updated with the real-time uptime status of GeekCircuit's online services and tools.">
    <meta property="og:image" content="https://assets.geekcircuit.com/img/logo/light.svg">
    <meta property="og:url" content="https://status.geekcircuit.com">
    <style>.logo div {display: none;}</style>
  theme: dark
  introTitle: "**GeekCircuit** Live Status Dashboard"
  introMessage: "Check the live status of our websites and tools. We keep everything running smoothly so you can focus on what matters."
  navbar:
    - title: Blog
      href: https://www.geekcircuit.com/
    - title: Web Tools
      href: https://tooloza.com/
  i18n:
  footer: &copy; 2024–2025 Geek Circuit. Powered by [@Upptime](https://upptime.js.org/).
