# Change these first
owner: GeekCircuitOfficial # Your GitHub organization or username, where this repository lives
repo: StatusPage # The name of this repository

sites:
- name: GeekCircuit
  url: https://www.geekcircuit.com/
  check: "https"
  port: 443
  ipv6: false

- name: Tooloza
  url: https://tooloza.com/
  check: "https"
  port: 443
  ipv6: false
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.geekcircuit.com
  # baseUrl: /StatusPage
  logoUrl: https://www.geekcircuit.com/wp-content/uploads/2025/04/logo_light.webp
  name: Geek Circuit
  customHeadHtml: "<style>.logo div {display: none;} .logo img { margin-left: -15px;}</style>"
  js: "document.addEventListener('DOMContentLoaded',()=>{const e=document.querySelector('footer p');e&&(e.innerHTML=`&copy; ${new Date().getFullYear()} GeekCircuit. All Rights Reserved.`)});"
  theme: light
  introTitle: "**GeekCircuit** monitors the health of our websites, powered by GitHub and Upptime."
  introMessage: Welcome to the live status page of **GeekCircuit**.
  navbar:
    - title: Blog
      href: https://www.geekcircuit.com/
    - title: Web Tools
      href: https://tooloza.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
