# Change these first
owner: GeekCircuitOfficial # Your GitHub organization or username, where this repository lives
repo: StatusPage # The name of this repository

sites:
  - name: Main Website
    url: https://www.geekcircuit.com/
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.geekcircuit.com
  # baseUrl: /StatusPage
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Website
      href: https://www.geekcircuit.com/
    - title: Tools
      href: https://www.geekcircuit.com/tools
    - title: GitHub
      href: https://github.com/$OWNER/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
