# Change these first
owner: GeekCircuitOfficial # Your GitHub organization or username, where this repository lives
repo: StatusPage # The name of this repository

sites:
- name: GeekCircuit
  url: https://www.geekcircuit.com/
  check: "https"
  port: 443
  ipv6: false
  icon: https://assets.geekcircuit.com/img/favicon/favicon.png

- name: Tooloza
  url: https://tooloza.com/
  check: "https"
  port: 443
  ipv6: false

status-website:
  cname: status.geekcircuit.com
  favicon: https://assets.geekcircuit.com/img/favicon/favicon.png
  logoUrl: https://assets.geekcircuit.com/img/logo/png/light.png
  name: Geek Circuit
  customHeadHtml: |
    <meta name="description" content="Stay updated with the real-time status of our websites, tools, and services. We monitor everything so you don't have to.">
    <meta name="keywords" content="Geek Circuit, Status, Monitoring, Uptime, India">
    <meta property="og:title" content="Geek Circuit Status Page">
    <meta property="og:description" content="Stay updated with the real-time status of our websites, tools, and services. We monitor everything so you don't have to.">
    <meta property="og:image" content="https://assets.geekcircuit.com/img/logo/png/light.png">
    <meta property="og:url" content="https://status.geekcircuit.com">
    <style>.logo div {display: none;}</style>
  theme: light
  introTitle: "Geek Circuit **Status Dashboard**"
  introMessage: "Stay updated with the real-time status of our websites, tools, and services. We monitor everything so you don't have to."
  navbar:
    - title: Blog
      href: https://geekcircuit.com/
    - title: Tooloza 🛠️
      href: https://tooloza.com/
i18n:
  footer: "&copy; 2024–2025 Geek Circuit. <a href='https://madewithloveinindia.org' target='_blank'>Made with <span aria-label='Love' style='color: #f43f5e'>&hearts;</span> in India</a>."
